name: Tests Clickhouse

on:
  push:
    branches:
      - develop
  pull_request:
    branches-ignore:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    services:
      clickhouse:
        image: clickhouse/clickhouse-server
        env:
          TZ: UTC
        ports:
          - 8123:8123
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false
          cache-overwrite-existing: true

      - name: Run Integration Tests with Coverage
        run: |
          ./gradlew test

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/reports/jacoco/test/*.xml
          fail_ci_if_error: true
